export const DIFF_COORDS = {
	TOP: [0, -1],
	RIGHT_TOP: [1, -1],
	RIGHT: [1, 0],
	RIGHT_BOTTOM: [1, 1],
	BOTTOM: [0, 1],
	LEFT_BOTTOM: [-1, 1],
	LEFT: [-1, 0],
	LEFT_TOP: [-1, -1],
};

export const DIFF_AROUND = Object.values(DIFF_COORDS);

const DIFF_TOP_MIDDLE = [
	DIFF_COORDS.LEFT,
	DIFF_COORDS.LEFT_TOP,
	DIFF_COORDS.TOP,
	DIFF_COORDS.RIGHT_TOP,
	DIFF_COORDS.RIGHT,
];
const DIFF_MIDDLE_VERTICAL = [DIFF_COORDS.RIGHT, DIFF_COORDS.LEFT];
const DIFF_BOTTOM_MIDDLE = [
	DIFF_COORDS.LEFT,
	DIFF_COORDS.LEFT_BOTTOM,
	DIFF_COORDS.BOTTOM,
	DIFF_COORDS.RIGHT_BOTTOM,
	DIFF_COORDS.RIGHT,
];
export const DIFF_VERTICAL = [DIFF_TOP_MIDDLE, DIFF_MIDDLE_VERTICAL, DIFF_BOTTOM_MIDDLE];

const DIFF_LEFT_MIDDLE = [
	DIFF_COORDS.TOP,
	DIFF_COORDS.LEFT_TOP,
	DIFF_COORDS.LEFT,
	DIFF_COORDS.LEFT_BOTTOM,
	DIFF_COORDS.BOTTOM,
];
const DIFF_MIDDLE_HORIZONTAL = [DIFF_COORDS.TOP, DIFF_COORDS.BOTTOM];
const DIFF_RIGHT_MIDDLE = [
	DIFF_COORDS.TOP,
	DIFF_COORDS.RIGHT_TOP,
	DIFF_COORDS.RIGHT,
	DIFF_COORDS.RIGHT_BOTTOM,
	DIFF_COORDS.BOTTOM,
];
export const DIFF_HORIZONTAL = [DIFF_LEFT_MIDDLE, DIFF_MIDDLE_HORIZONTAL, DIFF_RIGHT_MIDDLE];

export const DIFF_MIDDLE_INDEX = 1;
export const DIFF_LAST_INDEX = 2;
